---
title: "Untitled"
output: html_document
date: "2025-05-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Comparing the predicted targets with significant genes in the TWAS paper

```{r message=FALSE, warning=FALSE}
twas_path <- "data/twas/"

all_unique  <- list()
all_analyses <- list()

# List all subdirectories inside the main directory
subdirs <- list.dirs(twas_path, recursive = FALSE)

# Loop through each subdirectory
for (subdir in subdirs) {

  analyses_genes <- list()
  unique_genes <- c()
  
  # Find the CSV file in the subdirectory
  csv_files <- list.files(subdir, pattern = "\\.csv$", full.names = TRUE)
  
  # If there's at least one CSV file, read it
  if (length(csv_files) > 0) {
    csv_path <- csv_files[1]  # Assuming there's only one CSV per folder
    
    # Extract the file name without extension
    file_name <- tools::file_path_sans_ext(basename(csv_path))
    
    data <- read.csv(csv_path, header = TRUE)
    
    for (col in colnames(data)){
      genes <- unique(data[[col]])
      analyses_genes[[col]] <- genes
      unique_genes <- unique(c(unique_genes, genes))
    }
    
    all_analyses[[file_name]] <- analyses_genes
    all_unique[[file_name]] <- unique_genes
    
  } else {
    warning(paste("No CSV file found in", subdir))
  }
}
```


```{r}
# Ler cada arquivo CSV e fazer interseção com snrnaseq_intersection
csv_folder <- "./data/target_prediction/intersections"
csv_files <- list.files(csv_folder, pattern = "\\.csv$", full.names = TRUE)

# Lista para guardar os resultados
intersection_results <- list()
intersection_results_outro <- list()
for (file in csv_files) {
  # Read raw lines first
  raw_lines <- readLines(file, warn = FALSE)

  # Nome base do arquivo para usar como key
  key <- gsub("^intersection_|\\.csv$", "", basename(file))
  
  # Ler CSV
  # print(file)
  df <- read.csv(file, stringsAsFactors = FALSE)
  # print(file)
  # Garantir vetor
  vec <- as.character(df$target)
  
  # Interseção com snrnaseq_intersection
  for (twas in names(all_unique)){
    genes_twas <- all_unique[[twas]]
    key <- paste0(basename(file), twas)
    inter <- intersect(vec, genes_twas)
    intersection_results[[key]] <- inter
  }
}
```

```{r}
library(ggplot2)
sizes <- lengths(intersection_results)
df_sizes <- data.frame(N_alvos = sizes)

p_dist_twas <- ggplot(df_sizes, aes(x = N_alvos)) +
  geom_histogram(binwidth = 1, fill = "#6FAF9C", color = "white") +
  theme_classic() +
  labs(
    x = "Número de alvos",
    y = "Frequência"
  ) +
  theme(
    legend.position = "top",
    plot.subtitle = element_text(size = 14L),
    axis.title.y = element_text(size = 14L),
    axis.title.x = element_text(size = 14L),
    axis.text.y = element_text(size = 14L),
    axis.text.x = element_text(size = 14L),
    legend.text = element_text(size = 14L),
    legend.title = element_text(size = 14L)
    )

# ggsave("dist.png", width = 3, height = 2)

library(patchwork)

p_dist <- (p_dist_degs | p_dist_twas) + plot_annotation(tag_levels = "a")
ggsave("dist_alvos_2.png", width = 6, height = 3)
```


```{r}
library(dplyr)

# all_unique: lista nomeada; cada elemento = vetor de genes de um autor
# nomes da lista = Adams2025, etc.

gene_author <- bind_rows(
  lapply(names(all_unique), function(auth) {
    data.frame(
      gene   = all_unique[[auth]],
      author = auth,
      stringsAsFactors = FALSE
    )
  })
)

# remover NAs ou strings vazias se existirem
gene_author <- gene_author %>%
  filter(!is.na(gene), gene != "")

genes_autores <- gene_author %>%
  group_by(gene) %>%
  summarise(
    n_autores = n_distinct(author),
    autores   = paste(sort(unique(author)), collapse = ", ")
  ) 

genes_autores_filtrado <- genes_autores %>%
  filter(n_autores > 1) %>%
  arrange(desc(n_autores), gene)

all_intersects <- unique(unname(unlist(intersection_results)))
genes_autores_alvos <- genes_autores %>%
  filter(gene %in% all_intersects) %>%
  arrange(desc(n_autores), gene)

genes_autores_alvos_filtrado <- genes_autores_alvos %>%
  filter(n_autores > 1)
```



# Comparing with previous analyses

```{r}
load("./sct/degs_sct_celltype/results_sct_celltype.RData")
load("./sct/degs_sct_novo/results_sct.RData")
load("./rnaseq/deg_outputs/results_214951.RData")
load("./data/snrnaseq/results_logn.RData")
load("./data/snrnaseq/results_logn_celltype.RData")

all_sct_celltype <- unique(unlist(unname(results_sct_celltype)))
all_sct <- unique(unlist(unname(results_sct)))
all_214951 <- unique(unlist(unname(results_214951)))
all_logn <- unique(unlist(unname(results_logn)))
all_logn_celltype <- unique(unlist(unname(results_logn_celltype)))
all_twas <- genes_autores_alvos_filtrado$gene

all_results <- list(all_sct, all_sct_celltype, all_logn, all_logn_celltype, all_214951, all_twas)

# Define names for the analyses
analysis_names <- c("SCT-pseudobulk", "SCT-celltype", "logn-pseudobulk", "logn-celltype", "214951", "TWAS")
names(all_results) <- analysis_names

# Create a named list of all genes with their corresponding analysis
gene_to_analyses <- list()

for (i in seq_along(all_results)) {
  genes <- all_results[[i]]
  analysis <- analysis_names[i]
  
  for (gene in genes) {
    gene_to_analyses[[gene]] <- unique(c(gene_to_analyses[[gene]], analysis))
  }
}

gene_analyses_df <- tibble::tibble(
  gene = names(gene_to_analyses),
  analyses = sapply(gene_to_analyses, function(x) paste(sort(x), collapse = ","))
)

multi_analysis_genes <- gene_analyses_df %>% 
  filter(lengths(gene_to_analyses) > 1)
```

# Getting the predicted metabolites/ligands for the intersection genes

```{r}
load("~/Documents/vitoria/usp-masters/sct/degs_sct_novo/degs_f.RData")
load("~/Documents/vitoria/usp-masters/sct/degs_sct_celltype/GSE213982_celltype_f.RData")
load("~/Documents/vitoria/usp-masters/sct/degs_sct_celltype/GSE144136_celltype_f.RData")

rownames(degs_GSE144136_f) <- degs_GSE144136_f$X
all_targets <- read.table("data/targets.txt")$V1

for (gene in all_targets){
  cat("\t",gene, "\n")
  if (gene %in% rownames(GSE144136_celltype_filtered$InN) & gene %in% rownames(GSE213982_celltype_filtered$InN)){
    cat("inn ",GSE144136_celltype_filtered$InN[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$ExN) & gene %in% rownames(GSE213982_celltype_filtered$ExN)){
    cat("exn ",GSE144136_celltype_filtered$ExN[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$Oli) & gene %in% rownames(GSE213982_celltype_filtered$Oli)){
    cat("oli ",GSE144136_celltype_filtered$Oli[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$Ast) & gene %in% rownames(GSE213982_celltype_filtered$Ast)){
    cat("ast ",GSE144136_celltype_filtered$Ast[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$Mic) & gene %in% rownames(GSE144136_celltype_filtered$Mic)){
    cat("mic ",GSE144136_celltype_filtered$Mic[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$OPC) & gene %in% rownames(GSE213982_celltype_filtered$OPC)){
    cat("opc ",GSE144136_celltype_filtered$OPC[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% rownames(GSE144136_celltype_filtered$End) & gene %in% rownames(GSE213982_celltype_filtered$End)){
    cat("end ",GSE144136_celltype_filtered$End[gene, "avg_log2FC"], '\n')
  }
  if (gene %in% degs_GSE144136_f$X & gene %in% degs_GSE213982_f$X){
    cat("geral ",degs_GSE144136_f[gene, "avg_log2FC"], '\n')
  }
}
```
```{r}
setwd("~/Documents/vitoria/usp-masters/data/snrnaseq")
degs14 <- read_csv("~/Documents/vitoria/usp-masters/data/snrnaseq/GSE144136/degs/GSE144136_results_filtered.csv")$...1
degs21 <- read_csv("~/Documents/vitoria/usp-masters/data/snrnaseq/GSE213982/degs/GSE213982_results_filtered.csv")$...1

degs14_celltype <- unique(unlist(unname(sapply(GSE144136_celltype_filtered, function(df) rownames(df)))))
degs21_celltype <- unique(unlist(unname(sapply(GSE213982_celltype_filtered, function(df) rownames(df)))))

aaa <- Reduce(union, c(degs14, degs21, degs21_celltype, degs21_celltype))
```

```{r}
# Ler cada arquivo CSV e fazer interseção com snrnaseq_intersection
csv_folder <- "~/Documents/vitoria/usp-masters/data/target_prediction/intersections"
csv_files <- list.files(csv_folder, pattern = "\\.csv$", full.names = TRUE)

# Lista para guardar os resultados
intersection_results <- list()
for (file in csv_files) {
  # Read raw lines first
  raw_lines <- readLines(file, warn = FALSE)

  # Nome base do arquivo para usar como key
  key <- gsub("^intersection_|\\.csv$", "", basename(file))
  
  # Ler CSV
  # print(file)
  df <- read.csv(file, stringsAsFactors = FALSE)
  # print(file)
  # Garantir vetor
  vec <- as.character(df$target)
  
  # Interseção com snrnaseq_intersection

  inter <- intersect(vec, aaa)
  intersection_results[[key]] <- inter
}
```