---
title: "vitoria"
author: "vitoria"
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ChemmineR)
library(ChemmineOB)
library(ggplot2)
```

### Convert data to format 'smiles compound_id' for SEA

```{r, include=FALSE}

# Read the CSV file
gutmgene <- read.csv("gutmgene.csv")

# Extract the pubchem_id from the "Metabolite (ID)" column
gutmgene <- gutmgene %>%
  mutate(pubchem_id = as.numeric(sub(".*\\((\\d+)(?:,.*)?\\)", "\\1", `Metabolite..ID.`))) %>%
  #mutate(pubchem_id = as.numeric(sub(".*\\((\\d+)(?:,.*)?\\)", "\\1", `Metabolite..ID.`)))
  filter(!is.na(pubchem_id)) %>%
  distinct(pubchem_id, .keep_all = TRUE)

# View the updated dataframe
any(is.na(gutmgene$pubchem_id))
```

```{r, include=FALSE}
pubchem_ids <- gutmgene$pubchem_id
compounds_sdf <- pubchemCidToSDF(pubchem_ids)  
compounds_smiles <- sdf2smiles(compounds_sdf)
```

### Get the intersection

```{r setup, include=FALSE}
predicted_targets <- intersect(targets_SEA, targets_STP)
```