>P1;PDE4B
structureX:PDE4B:1:A:+492:A:::-1.00:-1.00
VTPFAQVLASLRSVRNNFTILTNLHGTS-NKRSPAASQPPVSRVNPQEESYQKLAMETLEELDWCLDQLETIQTY
RSVSEMASNKFKRMLNRELTHLSEMSRSGNQVSEYISNTFLDKQNDVEIPSPTQKDREKKKKQQLMTQISGVKKL
MHSSSLNNTSISRFGVNTENEDHLAKELEDLNKWGLNIFNVAGYSHNRPLTCIMYAIFQERDLLKTFRISSDTFI
TYMMTLEDHYHSDVAYHNSLHAADVAQSTHVLLSTPALDAVFTDLEILAAIFAAAIHDVDHPGVSNQFLINTNSE
LALMYNDESVLENHHLAVGFKLLQEEHCDIFMNLTKKQRQTLRKMVIDMVLATDMSKHMSLLADLKTMVETKKVT
SSGVLLLDNYTDRIQVLRNMVHCADLSNPTKSLELYRQWTDRIMEEFFQQGDKERERGMEISPMCDKHTASVEKS
QVGFIDYIVHPLWETWADLVQPDAQDILDTLEDNRNWYQSMIP*

>P1;target
sequence::: :: :::-1.00:-1.00
VTPFAQVLASLRTVRNNFAALTNLQDRAPSKRSPMCNQPSINKATITEEAYQKLASETLEELDWCLDQLETLQTR
HSVSEMASNKFKRMLNRELTHLSEMSRSGNQVSEFISNTFLDKQHEVEIPSPTQKEKEKKKR-P-MSQISGVKKL
MHSSSLTNSSIPRFGVKTEQEDVLAKELEDVNKWGLHVFRIAELSGNRPLTVIMHTIFQERDLLKTFKIPVDTLI
TYLMTLEDHYHADVAYHNNIHAADVVQSTHVLLSTPALEAVFTDLEILAAIFASAIHDVDHPGVSNQFLINTNSE
LALMYNDSSVLENHHLAVGFKLLQEENCDIFQNLTKKQRQSLRKMVIDIVLATDMSKHMNLLADLKTMVETKKVT
SSGVLLLDNYSDRIQVLQNMVHCADLSNPTKPLQLYRQWTDRIMEEFFRQGDRERERGMEISPMCDKHNASVEKS
QVGFIDYIVHPLWETWADLVHPDAQDILDTLEDNREWYQSTIP*

>P1;1TBB_nohetatm
structureX:1TBB_nohetatm:0:B:+326:B:::-1.00:-1.00
--EQEDVLA------------KELED--------------VNK--------------------WGL---------
-----------------HVFRIAELS--GN-------------------------------RPLTVI------MH
TIF--------------QERDLLK-----------TFKI-------PVDTLITYLMTLEDHYHA-----D--VAY
--------------HNNIHAADVVQSTHVLLSTPALEAVFTDLEILAAIFASAIHDVDHPGVSNQFLINTNSELA
LMYNDSSVLENHHLAVGFKLLQEENCDIFQNLTKKQRQSLRKMVIDIVLATDMSKHMNLLADLKTMVETKKVTSS
GVLLLDNYSDRIQVLQNMVHCADLSNPTKPLQLYRQWTDRIMEEFFRQGDRERERGMEISPMCDKHNASVEKSQV
GFIDYIVHPLWETWADLVHPDAQDILDTLEDNREWYQSTIPQ*