
>P1;1TBB_nohetatm
structureX:1TBB_nohetatm:0:B:+326:B:::-1.00:-1.00
--EQEDVLA------------KELED--------------VNK--------------------WGL---------
-----------------HVFRIAELS--GN-------------------------------RPLTVI------MH
TIF--------------QERDLLK-----------TFKI-------PVDTLITYLMTLEDHYHA-----D--VAY
--------------HNNIHAADVVQSTHVLLSTPALEAVFTDLEILAAIFASAIHDVDHPGVSNQFLINTNSELA
LMYNDSSVLENHHLAVGFKLLQEENCDIFQNLTKKQRQSLRKMVIDIVLATDMSKHMNLLADLKTMVETKKVTSS
GVLLLDNYSDRIQVLQNMVHCADLSNPTKPLQLYRQWTDRIMEEFFRQGDRERERGMEISPMCDKHNASVEKSQV
GFIDYIVHPLWETWADLVHPDAQDILDTLEDNREWYQSTIPQ*

>P1;target
sequence::: :: :::-1.00:-1.00
VTPFAQVLASLRTVRNNFAALTNLQDRAPSKRSPMCNQPSINKATITEEAYQKLASETLEELDWCLDQLETLQTR
HSVSEMASNKFKRMLNRELTHLSEMSRSGNQVSEFISNTFLDKQHEVEIPSPTQKEKEKKKRPMSQISGVKKLMH
SSSLTNSSIPRFGVKTEQEDVLAKELEDVNKWGLHVFRIAELSGNRPLTVIMHTIFQERDLLKTFKIPVDTLITY
LMTLEDHYHADVAYHNNIHAADVVQSTHVLLSTPALEAVFTDLEILAAIFASAIHDVDHPGVSNQFLINTNSELA
LMYNDSSVLENHHLAVGFKLLQEENCDIFQNLTKKQRQSLRKMVIDIVLATDMSKHMNLLADLKTMVETKKVTSS
GVLLLDNYSDRIQVLQNMVHCADLSNPTKPLQLYRQWTDRIMEEFFRQGDRERERGMEISPMCDKHNASVEKSQV
GFIDYIVHPLWETWADLVHPDAQDILDTLEDNREWYQSTIP-*
